import { ScaledSheet,ms } from "react-native-size-matters";
import {themeGreenColor,primaryTextColor,lineColor, blockColor9, blockColor6,pageBg} from '@/contents/theme'

const styles = ScaledSheet.create({
  pageHeader:{
    flexDirection:'row',
    alignItems:'center',
    paddingHorizontal:ms(15),
    position:'relative',
    // backgroundColor:'white'
  },
  backBtn:{
    zIndex:1,
    position:'relative',
    marginLeft:'-5@ms'
  },
  pageTitle:{
    position:'absolute',
    left:80,
    right:80,
    bottom:0,
    zIndex:1,
    justifyContent:'center',
    alignItems:'center',
  },
  pageTitleText:{
    textAlign:'center',
    color:'#000',
    fontSize:ms(18),
  },
  headerBg:{
    position:'absolute',
    left:0,
    right:0,
    top:0,
    bottom:0,
    backgroundColor:'white',
  },
  topContainer:{
    paddingVertical:ms(20),
    // paddingHorizontal:ms(16),
  },
  userInfo:{
    flexDirection:'row',
    
    alignItems:'center'
  },
  avatar:{
    width:ms(20),
    height:ms(20),
    marginRight:ms(8)
  },
  billDate:{
    fontSize:ms(22),
    paddingVertical:ms(15),
    fontWeight:600
  },
  slog:{
    fontSize:ms(11)
  },
  summaryBox:{
    backgroundColor:'white',
    padding:ms(16),
    borderRadius:ms(8),
    marginTop:ms(10),
    marginHorizontal:ms(-5),
    overflow:'hidden'
  },
  summarTop:{
    // flexDirection:'row',
  },
  summaryTopView:{
    flexDirection:'row',
  },
  summaryTopLabel:{
    flex:1,
    color:blockColor9,
    fontSize:ms(11)
  },
  summaryTopValue:{
    flex:1,
    fontSize:ms(24),
    fontWeight:500,
    color:'#000'
  },
  summarContent:{
    marginTop:ms(20)
  },
  suammryInfo:{
    flexDirection:'row',
    marginVertical:ms(8),
    alignItems:'center'
  },
  summaryLabel:{
    fontSize:ms(10),
    color:'#AEAEAE',
    marginRight:ms(10)
  },
  summaryLineView:{
    width:ms(150),
    flexDirection:'row',
    alignItems:'center'
  },
  summaryLine:{
    height:ms(10),
    borderRadius:ms(10),
    backgroundColor:themeGreenColor,
    minWidth:ms(10)
  },
  summaryAmount:{
    fontSize:ms(10),
    marginLeft:ms(10),
    fontWeight:300
  },
  boxTitle:{
    fontWeight:600,
    fontSize:ms(14),
    marginTop:ms(5)
  },
  pieBox:{
    paddingVertical:ms(30),
    flexDirection:'row',
    alignItems:'center'
  },
  pieInfo:{
    marginLeft:ms(30),
    flex:1
  },
  pieLine:{
    flexDirection:'row',
    alignItems:'center',
    marginVertical:ms(3)
  },
  pieInfoTitle:{
    color:'#AEAEAE',
    fontSize:ms(10)
  },
  pieLineItem1:{
    flex:1,

  },
  pieLineItem2:{
    width:'20%',
    textAlign:'right',
  },
  pieLineItem3:{
    width:'35%',
    textAlign:'right',
  },
  pieLineClassify:{
    flexDirection:'row',
    alignItems:'center'
  },
  rankTop:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    paddingVertical:ms(10)
  },
  showMoreBtn:{
    flexDirection:'row',
    alignItems:'center'
  },
  showMoreBtnText:{
    fontSize:ms(11),
    color:blockColor9,
    marginRight:ms(5)
  },
  subTitle:{
    color:blockColor9
  },
  rankBox:{},
  rankItem:{
    flexDirection:'row',
    alignItems:'center',
    paddingVertical:ms(10)
  },
  rankId:{
    fontSize:ms(13)
  },
  iconCircle:{
    width:ms(30),
    height:ms(30),
    borderRadius:ms(30),
    backgroundColor:pageBg,
    alignItems:'center',
    justifyContent:'center',
    marginHorizontal:ms(15)
  },
  icon:{
    width:ms(20),
    height:ms(20)
  },
  itemText:{
    justifyContent:'center',
    flex:1
  },
  itemLabel:{
    fontSize:ms(12)
  },
  itemDate:{
    fontSize:ms(10),
    color:blockColor9
  },
  itemAmount:{
    fontSize:ms(12),
    fontWeight:500,
    color:'black'
  },
  infoBox:{
    flexDirection:'row',
    marginVertical:ms(20)
  },
  leftView:{
    marginRight:ms(40)
  },
  infoLabel:{
    fontSize:ms(10),
    color:blockColor9
  },
  infoValue:{
    color:'black',
    fontSize:ms(16),
    fontWeight:500,
    marginVertical:ms(8),
    // transform: [{ scaleY: 1.4 }],
  },
  infoDate:{
    fontSize:ms(10),
    color:blockColor9
  },
  lineChartBox:{},
  barChartBox:{
    flexDirection:'row',
    paddingTop:ms(60),
    paddingBottom:ms(30)
  },
  barChartItem:{
    flex:1,
    borderBottomColor:lineColor,
    borderBottomWidth:0.5,
    justifyContent:'flex-end',
    alignItems:'center',
    height:ms(150),
    
  },
  barChartItemBg:{
    width:ms(18),
    borderTopRightRadius:ms(5),
    borderTopLeftRadius:ms(5),
    backgroundColor:themeGreenColor,
    minHeight:ms(5)
  },
  barValue:{
    fontSize:ms(9),
    marginBottom:ms(5),
    color:'rgba(0,0,0,0.7)'
  },
  barLabel:{
    position:'absolute',
    bottom:ms(-20),
    fontSize:ms(9),
    color:blockColor9
  },
  contrastBox:{
    paddingTop:ms(30)
  },
  contrastBoxTitle:{
    color:blockColor9,
    fontSize:ms(12)
  },
  contrastItemRight:{
    flexDirection:'row',
    alignItems:'center'
  },
  contrastText:{
    color:blockColor6,
    fontSize:ms(12),
    marginLeft:ms(10),
    marginRight:ms(5)
  },
  upAndDown:{
    width:ms(12),
    height:ms(12)
  },
  achievement:{
    flexDirection:'row',
    paddingTop:ms(30)
  },
  achievementItem:{
    flex:1,
    alignItems:'center'
  },
  achievementItemValue:{
    fontWeight:500,
    color:'black',
    fontSize:ms(20)
    
  },
  achievementItemLabel:{
    marginTop:ms(5),
    color:blockColor9,
    fontSize:ms(10)
  }
})
export default styles