import { ScaledSheet } from 'react-native-size-matters'
import {
  pageBg,
  themeGreenColor,
  lineColor,
  backgroundColor,
  blockColor9,
} from '@/contents/theme'

const styles = ScaledSheet.create({
  container: {
    flex: 1,
    paddingTop: '16@ms',
  },
  item: {
    width: '25%',
    justifyContent: 'center',
    alignItems: 'center',
    height: '90@ms',
  },
  itemCircle: {
    alignItems: 'center',
    width: '50@ms',
    height: '50@ms',
    backgroundColor: '#eee',
    borderRadius: '25@ms',
    justifyContent: 'center',
  },
  itemCircleActive: {
    alignItems: 'center',
    width: '50@ms',
    height: '50@ms',
    borderRadius: '25@ms',
    justifyContent: 'center',
    backgroundColor: themeGreenColor,
  },
  itemText: {
    fontSize: '12@ms',
    marginTop: '3@ms',
  },
  valueView: {
    flexDirection: 'row',
    borderBottomWidth: '1@ms',
    marginLeft: '30@ms',
    borderBottomColor: themeGreenColor,
    alignItems: 'center',
    paddingVertical: '10@ms',
    paddingRight: '16@ms',
  },
  inputView: {
    flex: 1,
  },
  valueText: {
    position: 'absolute',
    fontSize: '36@ms',
    color: 'transparent',
    fontWeight: 300,
    left: 0,
    top: 0,
    bottom: 0,
    right: 0,
  },
  inputText: {
    fontSize: '36@ms',
    color: themeGreenColor,
    fontWeight: 300,
  },
  amountText: {
    position: 'absolute',
    fontSize: '36@ms',
    color: themeGreenColor,
    fontWeight: 300,
    left: 0,
    top: 0,
    bottom: 0,
    right: 0,
  },
  valueButton: {
    position: 'relative',
    backgroundColor: '#f0f3f8',
    borderRadius: '6@ms',
    justifyContent: 'center',
    alignItems: 'center',
    width: '46@ms',
    height: '46@ms',
  },
  bottonText: {
    fontSize: '9@ms',
    marginTop: '4@ms',
    color: blockColor9,
  },
  formItem: {
    flexDirection: 'row',
    borderBottomWidth: '0.5@ms',
    borderBlockColor: lineColor,
    height: '50@ms',
    alignItems: 'center',
    marginLeft: '30@ms',
  },
  formLabel: {
    color: blockColor9,
    fontSize: '12@ms',
    marginHorizontal: '10@ms',
  },
  formValue: {
    flex: 1,
    fontSize: '14@ms',
    marginLeft: '5@ms',
  },

  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: '10@ms',
    borderTopRightRadius: '10@ms',
    overflow: 'hidden',
    height: '400@ms',
  },
  modalItem: {
    height: '48@ms',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: '16@ms',
    borderBottomColor: lineColor,
    borderBottomWidth: '0.5@ms',
  },
  modalText: {
    marginLeft: '10@ms',
  },
  contentHeader: {
    height: '50@ms',
    paddingHorizontal: '16@ms',
    justifyContent: 'center',
    backgroundColor: backgroundColor,
  },
  contentTitle: {},
  iconCircle: {
    width: '30@ms',
    height: '30@ms',
    borderRadius: '15@ms',
    backgroundColor: '#eee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: '20@ms',
    paddingHorizontal: '16@ms',
  },
  footerButton: {
    backgroundColor: '#f0f3f8',
    borderRadius: '20@ms',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: '40@ms',
  },
  footerButtonCancel: {
    marginRight: '10@ms',
  },
  footerButtonSave: {
    marginLeft: '10@ms',
    backgroundColor: themeGreenColor,
  },
  footerButtonCancelText: {
    color: blockColor9,
    fontSize: '14@ms',
  },
  footerButtonSaveText: {
    color: 'white',
    fontSize: '14@ms',
  },
  imagesLength: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    padding: '3@ms',
    color: '#fff',
    backgroundColor: 'rgba(0,0,0,.2)',
    zIndex: 999,
    borderRadius: '6@ms',
  },
  btnImage: {
    width: '46@ms',
    height: '46@ms',
    borderRadius: '6@ms',
    zIndex: 98,
  },
  bgView: {
    position: 'absolute',
    left: '100%',
    borderTopRightRadius: '4@ms',
    borderBottomRightRadius: '4@ms',
  },
  bgView1: {
    width: '4@ms',
    top: '4@ms',
    bottom: '4@ms',
    zIndex: 9,
    backgroundColor: '#ccc',
  },
  bgView2: {
    width: '8@ms',
    top: '8@ms',
    bottom: '8@ms',
    zIndex: 1,
    backgroundColor: '#e3e4e5',
  },
})
export default styles
